environment:
  development: true

replicaCount: 1

image:
  repository: 254652353999.dkr.ecr.us-east-1.amazonaws.com/clinic-appointment
  tag: ""
  pullPolicy: IfNotPresent

  # reference the image pull secret created by Ansible
  pullSecrets:
    - name: ecr-registry

django:
  secretKey: ""
  csrfTrustedOrigins:
    - http://localhost

database:
  password: dev-password
  storage:
    size: 2Gi

ingress:
  enabled: false

nginx:
  image:
    repository: 254652353999.dkr.ecr.us-east-1.amazonaws.com/clinic-appointment
    tag: ""
    pullPolicy: IfNotPresent

hpa:
  enabled: false
