apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "clinic.webName" . }}
  labels:
    {{- include "clinic.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "clinic.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "clinic.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.web.containerPort }}
          envFrom:
            - configMapRef:
                name: {{ include "clinic.fullname" . }}-config
            - secretRef:
                name: {{ include "clinic.fullname" . }}-secret
          volumeMounts:
            - name: media
              mountPath: /app/media
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: {{ include "clinic.fullname" . }}-media
