apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "clinic.fullname" . }}-media
  labels:
    {{- include "clinic.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.media.accessMode }}
  {{- if .Values.persistence.media.storageClassName }}
  storageClassName: {{ .Values.persistence.media.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.media.size }}
