---
- name: Configure clinic appointment infrastructure host
  hosts: all
  become: true
  roles:
    - java
    - docker
    - kubectl
    - helm
    - nginx_controller
    - awscli
    - jenkins
    - handlers
